#!/bin/bash
#
# Ernest Kugel, 2020

PRGNAM='zabbix_agent'
VERSION='4.0.20'
APP_URL="https://cdn.zabbix.com/zabbix/sources/stable/4.0/zabbix-${VERSION}.tar.gz"
BUILD_DIR="/tmp/SlackBuild-${PRGNAM}-$(date +%s)"
TAG='1'

set -e

# Check for 64 bit system
if [ "$(getconf LONG_BIT)" == "64" ]; then
        LIBDIRSUFFIX="64"
else
        LIBDIRSUFFIX=""
fi

# Get source
if [ ! -f ./zabbix-${VERSION}.tar.gz ]; then
	wget ${APP_URL}
fi
if [ -d ./zabbix-${VERSION} ]; then
        rm -rf ./zabbix-${VERSION}
fi
tar -vxf ./zabbix-${VERSION}.tar.gz

mkdir -vp ${BUILD_DIR}/install ${BUILD_DIR}/src ${BUILD_DIR}/etc 
cp -v ./slack-desc ${BUILD_DIR}/install/slack-desc
cp -aRv ./zabbix-${VERSION} ${BUILD_DIR}/src
cp -v ${BUILD_DIR}/src/zabbix-${VERSION}/conf/zabbix_agentd.conf ${BUILD_DIR}/etc
chown -Rc root:root ${BUILD_DIR}

# Build
cd ${BUILD_DIR}/src/zabbix-${VERSION}
./configure --prefix=/usr \
        --libdir=/usr/lib${LIBDIRSUFFIX} \
        --sysconfdir=/etc \
        --enable-agent
make install -j$(grep -Pc 'processor\t:[0-9]*' /proc/cpuinfo) DESTDIR=${BUILD_DIR}
cd ${BUILD_DIR} 
rm -vrf ${BUILD_DIR}/src

# Create package
/sbin/makepkg -l y -p -c n /tmp/${PRGNAM}-${VERSION}-$(uname -m)-${TAG}.txz
rm -rf ${BUILD_DIR}
