#!/bin/bash
#
# Ernest Kugel, 2014

PRGNAM="qbittorrent"
VERSION="3.2.5"
GIT_TAG="release-${VERSION}"
APP_URL="https://github.com/qbittorrent/qBittorrent.git"
BUILD_DIR=/tmp/SlackBuild-${PRGNAM}-$(date +%s)
TAG=1

set -e

source ../functions.sh

git-pull ${PRGNAM} ${APP_URL} ${GIT_TAG}

stage ${PRGNAM} ${BUILD_DIR}

mkdir -v -p ${BUILD_DIR}/etc/rc.d
cp -v -f ./rc.qbittorrent ${BUILD_DIR}/etc/rc.d/rc.qbittorrent

build ${PRGNAM} ${VERSION} ${TAG} ${BUILD_DIR} '--disable-gui' ' '
