#!/bin/bash -e
#
# Ernest Kugel 2014/01/11

BUILD=1
VERSION=4.2.7p410
BUILD_DIR=/tmp/build-$(date +%s)

mkdir -pv ${BUILD_DIR}/install
cp -vf slack-desc ${BUILD_DIR}/install

if ! [ -f ntp-dev-4.2.7p410.tar.gz ]; then
  wget http://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ntp-dev/ntp-dev-${VERSION}.tar.gz
fi
tar vxzf ntp-dev-${VERSION}.tar.gz
cd ntp-dev-${VERSION}
./configure --prefix=/opt/ntp-dev-${VERSION} --with-memlock
make V=99 || exit 1
make check || exit 1
make install DESTDIR=${BUILD_DIR} || exit 1
rm -rf ../ntp-dev-${VERSION}

cd ${BUILD_DIR}
/sbin/makepkg -l y -c n /tmp/ntp-dev-${VERSION}-$(uname -m)-${BUILD}.txz
rm -rf ${BUILD_DIR}

exit 0
