#!/bin/bash
#
# Ernest Kugel, 2017

PRGNAM="docker-compose"
VERSION="1.10.0"
APP_URL="https://github.com/docker/compose/releases/download/${VERSION}/${PRGNAM}-$(uname -s)-$(uname -m)"
BUILD_DIR=/tmp/SlackBuild-${PRGNAM}-$(date +%s)
TAG=1_SBx

set -e

source ../functions-2.0.sh

stage ${BUILD_DIR}
if ! [ -f ./${PRGNAM} ]; then
	wget ${APP_URL}
fi

mkdir -v -p ${BUILD_DIR}/usr/bin
chmod +x ./${PRGNAM}
cp -v -f ./${PRGNAM} ${BUILD_DIR}/usr/bin

package ${PRGNAM} ${BUILD_DIR} ${VERSION} ${TAG}
