#!/bin/bash
#
# Ernest Kugel, 2014
PRGNAM="xburst_tools"
VERSION='0.0+201002-1'
BUILD_DIR=/tmp/SlackBuild-${PRGNAM}-$(date +%s)
TAG=1_SBx

set -e

mkdir -p ${BUILD_DIR}/install
cp ./slack-desc ${BUILD_DIR}/install/
wget http://projects.qi-hardware.com/media/upload/xburst-tools/files/xburst-tools_${VERSION}_amd64.bin.tar.bz2 -O- | tar -j -x -v -f- -C ${BUILD_DIR}
cd ${BUILD_DIR}
/sbin/makepkg -l y -c n /tmp/${PRGNAM}-${VERSION}-$(uname -m)-${TAG}.txz
