#!/bin/bash
#
# Ernest Kugel, 2014

PRGNAM="libtorrent"
VERSION="1.0.10"
APP_URL=https://github.com/arvidn/libtorrent.git
GIT_TAG="libtorrent-1_0_10"
BUILD_DIR=/tmp/SlackBuild-${PRGNAM}-$(date +%s)
TAG="1_SBx"

set -e

source ../functions.sh

# Clone/Pull latest
git-pull ${PRGNAM} ${BUILD_DIR} ${APP_URL} ${GIT_TAG}

stage ./${PRGNAM} ${BUILD_DIR}

build ${PRGNAM} ${BUILD_DIR} ${VERSION} ${TAG} ' ' '-p'
