name: SlackBuild
description: 'Execute a SlackBuild script'
inputs:
  target:
    description: 'One or more packages to build, comma-delimited'
runs:
  using: 'docker'
  image: 'ghcr.io/erikkugel/slackbuild:latest'
  args:
    - ${{ inputs.target }}
