on:
  push:
    paths:
      - .github/workflows/slackbuild.yml
      - .github/actions/slackbuild/action.yml
  workflow_dispatch:

jobs:
  slackbuild:
    runs-on: [ubuntu-latest]
    steps:
      - id: checkout
        name: Checkout SlackBuilds
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - id: ghcr_login
        name: GitHub Container Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_pull
        name: Docker Pull
        run: |
          docker pull ghcr.io/erikkugel/slackbuild:0.0.1
          mkdir -v packages
      
      - id: slackbuild_alttab
        name: SlackBuild alttab
        uses: ./.github/actions/slackbuild
        with:
          target: "uthash,alttab"

      - id: upload_artifact
        name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./packages/*.txz
