on:
  push:
    paths:
      - .github/workflows/slackbuild.yml
      - .github/actions/slackbuild/action.yml
  workflow_dispatch:

jobs:
  slackbuild:
    runs-on: [ubuntu-latest]
    steps:
      - id: checkout
        name: Checkout SlackBuilds
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - id: debug
        run: |
          echo "PWD: $(pwd)"
          echo "LS: $(ls -alhR) .github"

      - id: alttab
        name: alttab
        uses: './.github/actions/slackbuild'
          with:
            target: 'uthash,alttab'
